# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_extendrpar_wrappers", use_symbols = TRUE, package_name = "extendrpar")

#' @docType package
#' @usage NULL
#' @useDynLib extendrpar, .registration = TRUE
NULL

#' @export
par_c_api_calls <- function() .Call(wrap__par_c_api_calls)

