# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_extendrpar_wrappers", use_symbols = TRUE, package_name = "extendrpar")

#' @docType package
#' @usage NULL
#' @useDynLib extendrpar, .registration = TRUE
NULL

#' @export
par_call_RCapi <- function(robj) .Call(wrap__par_call_RCapi, robj)

